
export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST";      
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";      
export const GET_PROJECT_FALIURE = "GET_PROJECT_FALIURE";      

export const POST_PROJECT_REQUEST = "POST_PROJECT_REQUEST";      
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS";      
export const POST_PROJECT_FALIURE = "POST_PROJECT_FALIURE"; 

export const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";      
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";      
export const UPDATE_PROJECT_FALIURE = "UPDATE_PROJECT_FALIURE"; 

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FALIURE = "DELETE_PROJECT_FALIURE";

export const POST_TIME_SUCCESS = "POST_TIME_SUCCESS";
export const POST_TIME_FALIURE = "POST_TIME_FALIURE";